import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const faqs = [
  { q: "How does the live smartwatch sync work?", a: "We use the Google Fit API to pull your real-time health data — steps, heart rate, SpO₂, calories — directly from your connected smartwatch every 5 seconds." },
  { q: "Is my health data secure?", a: "Yes. Your data is stored in a private MongoDB database tied to your account. We never share or sell your data to third parties." },
  { q: "How is the diet plan generated?", a: "Your diet plan is generated by Gemini AI using your actual last 7 days of fitness data — not generic templates. It considers your steps, calories, heart rate, weight, sleep, sugar, BP, and cholesterol." },
  { q: "Can I use this without a smartwatch?", a: "Yes. You can manually log your health data (sleep quality, sugar status, BP, cholesterol, activity level) from the dashboard and still get a personalized AI diet plan." },
  { q: "What smartwatches are supported?", a: "Any device that syncs with Google Fit works — including Wear OS watches, Fitbit, Garmin, Samsung Galaxy Watch, and many others." },
  { q: "Is this app free to use?", a: "Yes, Fitness Freak is completely free. No hidden charges, no premium tiers." },
];

const team = [
  { name: "Aakansha Aghav", role: "Full Stack Developer", emoji: "👩‍💻" },
  { name: "AI Assistant", role: "Diet Plan Engine (Gemini AI)", emoji: "🤖" },
];

const About = () => {
  const navigate = useNavigate();
  const [openFaq, setOpenFaq] = useState(null);

  return (
    <div style={s.page}>
      <div style={s.navbar}>
        <div style={s.brand}>🏋️ Fitness Freak</div>
        <button style={s.backBtn} onClick={() => navigate('/homedash')}>← Dashboard</button>
      </div>

      <div style={s.content}>
        {/* Hero */}
        <div style={s.hero}>
          <h1 style={s.heroTitle}>About Fitness Freak</h1>
          <p style={s.heroSub}>A real-time AI-powered fitness tracker that connects your smartwatch to personalized health insights</p>
        </div>

        {/* Mission */}
        <div style={s.missionGrid}>
          {[
            { icon: "🎯", title: "Our Mission", desc: "Empower individuals to take control of their health with real data, not guesswork. We bridge your smartwatch and AI to give you actionable, personalized guidance every day." },
            { icon: "🔬", title: "Science-Backed", desc: "Every diet recommendation is generated by Gemini AI using your actual biometric data — steps, heart rate, weight, sleep, and more — not static templates." },
            { icon: "🔒", title: "Privacy First", desc: "Your health data belongs to you. We store it securely and never share it. OAuth 2.0 ensures only you can authorize access to your Google Fit data." },
          ].map(({ icon, title, desc }) => (
            <div key={title} style={s.missionCard}>
              <div style={s.missionIcon}>{icon}</div>
              <h3 style={s.missionTitle}>{title}</h3>
              <p style={s.missionDesc}>{desc}</p>
            </div>
          ))}
        </div>

        {/* How it works */}
        <div style={s.section}>
          <h2 style={s.sectionTitle}>⚙️ How It Works</h2>
          <div style={s.stepsGrid}>
            {[
              { num: "1", title: "Sign Up", desc: "Create your free account in seconds." },
              { num: "2", title: "Connect Google Fit", desc: "Authorize access to your smartwatch data via Google OAuth." },
              { num: "3", title: "View Live Data", desc: "Your steps, heart rate, calories and SpO₂ update every 5 seconds." },
              { num: "4", title: "Log Daily Health", desc: "Add sleep quality, BP, sugar, cholesterol and activity level." },
              { num: "5", title: "Get AI Diet Plan", desc: "Gemini AI analyzes your 7-day data and generates a personalized plan." },
              { num: "6", title: "Track Progress", desc: "View weekly charts and day-by-day breakdowns in Fitness History." },
            ].map(({ num, title, desc }) => (
              <div key={num} style={s.stepCard}>
                <div style={s.stepNum}>{num}</div>
                <div style={s.stepTitle}>{title}</div>
                <div style={s.stepDesc}>{desc}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Features */}
        <div style={s.section}>
          <h2 style={s.sectionTitle}>✨ Key Features</h2>
          <div style={s.featureGrid}>
            {[
              { icon: "⌚", title: "Live Smartwatch Sync", desc: "Real-time data from Google Fit every 5 seconds", color: "#fff7ed" },
              { icon: "🤖", title: "AI Diet Plans", desc: "Gemini AI generates plans from your actual health data", color: "#fdf4ff" },
              { icon: "📊", title: "Fitness History", desc: "Weekly charts for steps, calories, heart rate and more", color: "#eff6ff" },
              { icon: "🍎", title: "Food Guide", desc: "Search real nutrition data for any food via Open Food Facts", color: "#f0fdf4" },
              { icon: "💬", title: "AI Chatbot", desc: "Ask any health or fitness question to your AI assistant", color: "#ecfdf5" },
              { icon: "👤", title: "Health Profile", desc: "Track your personal stats and health metrics over time", color: "#fef9c3" },
            ].map(({ icon, title, desc, color }) => (
              <div key={title} style={{ ...s.featureCard, background: color }}>
                <div style={s.featureIcon}>{icon}</div>
                <div style={s.featureTitle}>{title}</div>
                <div style={s.featureDesc}>{desc}</div>
              </div>
            ))}
          </div>
        </div>

        {/* FAQ */}
        <div style={s.section}>
          <h2 style={s.sectionTitle}>❓ Frequently Asked Questions</h2>
          <div style={s.faqList}>
            {faqs.map(({ q, a }, i) => (
              <div key={i} style={s.faqItem} onClick={() => setOpenFaq(openFaq === i ? null : i)}>
                <div style={s.faqQ}>
                  <span>{q}</span>
                  <span style={s.faqArrow}>{openFaq === i ? '▲' : '▼'}</span>
                </div>
                {openFaq === i && <div style={s.faqA}>{a}</div>}
              </div>
            ))}
          </div>
        </div>

        {/* Contact */}
        <div style={s.contactCard}>
          <h2 style={s.contactTitle}>📬 Get in Touch</h2>
          <div style={s.contactGrid}>
            <div>📧 contact@fitnessfreak.com</div>
            <div>📍 Health City, Fitness Country</div>
            <div>📞 +1 (123) 456-7890</div>
          </div>
        </div>
      </div>
    </div>
  );
};

const s = {
  page: { minHeight: '100vh', background: '#f8f9fb', fontFamily: "'Segoe UI', sans-serif" },
  navbar: { background: '#fff', padding: '14px 32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', boxShadow: '0 2px 12px rgba(0,0,0,0.07)', position: 'sticky', top: 0, zIndex: 100 },
  brand: { fontSize: '20px', fontWeight: '800', color: '#ff6b00' },
  backBtn: { background: 'transparent', border: '1.5px solid #e0e0e0', padding: '8px 16px', borderRadius: '8px', cursor: 'pointer', fontWeight: '600', fontSize: '13px', color: '#555' },
  content: { maxWidth: '1100px', margin: '0 auto', padding: '48px 24px' },
  hero: { textAlign: 'center', marginBottom: '48px', background: 'linear-gradient(135deg, #1c1c2e, #2d1b4e)', borderRadius: '20px', padding: '60px 40px' },
  heroTitle: { fontSize: '36px', fontWeight: '800', color: '#fff', margin: '0 0 12px' },
  heroSub: { fontSize: '16px', color: '#aaa', maxWidth: '600px', margin: '0 auto' },
  missionGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px', marginBottom: '48px' },
  missionCard: { background: '#fff', borderRadius: '16px', padding: '28px', boxShadow: '0 2px 12px rgba(0,0,0,0.06)' },
  missionIcon: { fontSize: '32px', marginBottom: '12px' },
  missionTitle: { fontSize: '17px', fontWeight: '700', color: '#1a1a1a', margin: '0 0 8px' },
  missionDesc: { fontSize: '14px', color: '#666', lineHeight: 1.6, margin: 0 },
  section: { marginBottom: '48px' },
  sectionTitle: { fontSize: '20px', fontWeight: '700', color: '#1a1a1a', marginBottom: '20px' },
  stepsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: '16px' },
  stepCard: { background: '#fff', borderRadius: '14px', padding: '20px', boxShadow: '0 2px 12px rgba(0,0,0,0.06)', textAlign: 'center' },
  stepNum: { width: '36px', height: '36px', borderRadius: '50%', background: 'linear-gradient(135deg, #ff6b00, #ff9a3c)', color: '#fff', fontWeight: '800', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 12px' },
  stepTitle: { fontSize: '14px', fontWeight: '700', color: '#1a1a1a', marginBottom: '6px' },
  stepDesc: { fontSize: '12px', color: '#888', lineHeight: 1.5 },
  featureGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '16px' },
  featureCard: { borderRadius: '14px', padding: '22px', boxShadow: '0 2px 12px rgba(0,0,0,0.06)' },
  featureIcon: { fontSize: '28px', marginBottom: '10px' },
  featureTitle: { fontSize: '15px', fontWeight: '700', color: '#1a1a1a', marginBottom: '6px' },
  featureDesc: { fontSize: '13px', color: '#666', lineHeight: 1.5 },
  faqList: { display: 'flex', flexDirection: 'column', gap: '10px' },
  faqItem: { background: '#fff', borderRadius: '12px', padding: '18px 20px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', cursor: 'pointer' },
  faqQ: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '15px', fontWeight: '600', color: '#1a1a1a' },
  faqArrow: { color: '#ff6b00', fontSize: '12px' },
  faqA: { marginTop: '12px', fontSize: '14px', color: '#666', lineHeight: 1.6, borderTop: '1px solid #f0f0f0', paddingTop: '12px' },
  contactCard: { background: 'linear-gradient(135deg, #ff6b00, #ff9a3c)', borderRadius: '16px', padding: '32px', textAlign: 'center', color: '#fff' },
  contactTitle: { fontSize: '20px', fontWeight: '700', margin: '0 0 16px' },
  contactGrid: { display: 'flex', justifyContent: 'center', gap: '32px', flexWrap: 'wrap', fontSize: '14px', fontWeight: '600' },
};

export default About;
